export const homeObjOne = {
  id: "sobre",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Quem é Manu?",
  headline: "Perereca, Demonho, Safada, Lindona...",
  description: "Saiba a história da cachorra que conquista o coração de todos que visitam o 301.",
  buttonLabel: "Conheça",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "alt",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "fotos",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Ela não anda, ela desfila!",
  headline: "Foto? Que foto?",
  description: "Apesar de não gostar muito de tirar fotos, ela sabe fazer boas poses.",
  buttonLabel: "Veja Mais",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "alt2",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "depoimentos",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "É a cachorra mais fofa do mundo!",
  headline: "Sei lá, é uma coisa de outro planeta.",
  description: "É como amor à primeira, segunda, terceira, quarta vista, só aumenta.",
  buttonLabel: "Vamos lá",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "alt3",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "tutores",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Quem ama, cuida.",
  headline: "Essa família é muito unida",
  description: "Conheça Yago e Igor, os tutores dessa coisa linda.",
  buttonLabel: "Conheça Mais",
  imgStart: true,
  img: require("../../images/svg-4.svg").default,
  alt: "alt2",
  dark: false,
  primary: false,
  darkText: true,
};
